### ISSUE TITLE
Animation issue 

### ISSUE THREAD

**Issue by solojuve1897** [RevenueCat/cordova-plugin-purchases#11]
Here's a recording:
https://drive.google.com/file/d/1x7P3vODb-pqnDc7OGyrRaZQIVEEinrHw/view

Look how there's a black stripe falling down when the Payment-options goes down. I don't think I have seen this when trying out other IAP Cordova-plugins.

This is on Android. 

Since Apples sandbox environment IAP is different (with dialogs popping up) than in production I don't know how it will look like for iOS yet. I'm still waiting for Apple to approve my app to test it.

**Comment by vegaro** [comment]
Hi! Thanks for reporting. This is actually outside of RevenueCat's control. We rely on the BillingClient that Google provides and they use a transparent activity to launch the billing flow that's probably causing that ugly effect you're seeing. I did a quick search and found this, which looks like a solution https://github.com/googlesamples/android-play-billing/issues/135

Let me know if that helps

Cheers!

**Comment by solojuve1897** [comment]
Thanks for the help! It worked. I also had to add the following to my manifest:

`xmlns:tools="http://schemas.android.com/tools"`

This is valuable information for anyone who cares about making their application feel and look good.
