### ISSUE TITLE
Price string format for French is wrong

### ISSUE THREAD

**Issue by riderx** [RevenueCat/cordova-plugin-purchases#128]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

**Describe the bug**
When in France, store price are not well formatted.
the symbol should be at the end of price string .
See below current display:
<img width="154" alt="Screenshot 2022-03-30 at 12 57 15" src="https://user-images.githubusercontent.com/4084527/160829247-59a905a4-bb12-4d6f-ab1f-58d6c5317596.png">
Good display in France:
<img width="141" alt="Screenshot 2022-03-30 at 12 57 19" src="https://user-images.githubusercontent.com/4084527/160829253-4039b946-c1f2-4f30-9189-0521eb4a7afe.png">

**Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: IOS and ANDROID
   2. SDK version: latest
   3. OS + version: latest
   4. XCode/Android Studio version: latest
   5. Framework (Cordova, Ionic, Ionic Native, etc): Cordova
   6. Framework version: latest
   7. How widespread is the issue. Percentage of devices affected. 100% of French devices
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
You can see this in other platforms too https://forum.squarespace.com/topic/203128-displaying-euro-currency-symbol-after-price-in-products-and-cart-pages/

**Comment by beylmk** [comment]
HI @riderx, thanks for alerting us to this. A question before I start digging...where are you pulling those screenshots from? Is this from our SDKs `price_string`, or somewhere in a store? 

In Android, we simply pass through the price from the Play Store, which should be properly formatted. Our formatting on iOS takes into account the locale of the product, which would be associated with the locale of the store. Keep in mind that the locale of the store may not match the location or language of the device...

**Comment by beylmk** [comment]
Thanks for following up @riderx glad you found the issue... let me know if we can help further.
