### ISSUE TITLE
0.1.0 makePurchase error inconsistent across platforms

### ISSUE THREAD

**Issue by solojuve1897** [RevenueCat/cordova-plugin-purchases#15]
On iOS I get the following:

`{"error":{"code":1,"message":"Purchase was cancelled.","underlyingErrorMessage":"Kan inte ansluta till iTunes Store","readable_error_code":1},"userCancelled":true}`

On Android the properties are not in an error-object.

This inconsistency wasn't there with previous version. Or am I missing something?

**Comment by solojuve1897** [comment]
Also on Android I get the readable_error_code PurchaseCancelledError while on iOS as you can see it only gives you the number 1.

**Comment by solojuve1897** [comment]
@vegaro

**Comment by vegaro** [comment]
Thanks for reporting @solojuve1897 

Just released https://github.com/RevenueCat/cordova-plugin-purchases/releases/tag/0.1.1 that should address these issues. Let me know if you encounter any other problem and sorry about the trouble these might have caused.

Cheers!
