### ISSUE TITLE
Problem uploading to App Store

### ISSUE THREAD

**Issue by emilyjeppson** [RevenueCat/cordova-plugin-purchases#2]
First of all, THANK YOU for adding cordova support to Revenue Cat. This was SUPER easy to implement!

However, I did encounter 1 problem - uploading my app to the app store. Steps to reproduce:

1 - In Xcode, go to Product -> Archive
2 - Follow the prompts to Distribute the app
3 - Receive an unsupported architecture error as described here:

https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86

I was able to get around this using the script provided in the link above, but it's a bit of a hack. I've uploaded my app successfully in the past, and the error message I received specifically said it was erring on Purchases.framework.

Once I got around that error, it told me that Purchases.framework was not in the "Frameworks" directory. I moved it there and was able to successfully upload the app at that point. So there are definitely some workarounds for this, but it may be something to look in to.

**Comment by vegaro** [comment]
Hey sorry about that and thanks for reporting! We added a script to strip the framework but forgot to mention it in the README. I added it to the iOS instructions in this commit 473bad6d438feec373f08d67dab3415b2894299d

Let us know if you find more issues or have any feedback!
