### ISSUE TITLE
Visual Studio 2017 Cordova project build fails after adding revenuecat cordova plugin

### ISSUE THREAD

**Issue by vmaverick99** [RevenueCat/cordova-plugin-purchases#20]
Hello,

I am using the Visual Studio 2017 Cordova template to create my android app.
I am able to build and generate apk and everything works just fine.

After I added the revenuecat cordova plugin, the build fails and give me the following error:

1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.
1>MSBUILD : cordova-build error :  > Could not find androidx.annotation:annotation:1.1.0.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
1>MSBUILD : cordova-build error :  https://jcenter.bintray.com/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
1>MSBUILD : cordova-build error :  file:/C:/ProgramData/Microsoft/AndroidSDK/25/extras/android/m2repository/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
1>MSBUILD : cordova-build error :  file:/C:/ProgramData/Microsoft/AndroidSDK/25/extras/android/m2repository/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
1>MSBUILD : cordova-build error :  Required by:
1>MSBUILD : cordova-build error :  :android:unspecified > com.revenuecat.purchases:purchases:2.3.0
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M

I tried removing the plugin and reinstalling it. Restarting visual studio and the machine, no luck.
I am stuck with this issue for a week now.

I am ready with my implementation but wanted to integrate the subscription and came across this beautiful plugin that has everything that I am looking for. 

Any pointer to a solution is highly appreciated.

Thank you in advance.

**Comment by vmaverick99** [comment]
Found the solution

**Comment by arjunkumar-udainath** [comment]
@vmaverick99 Can you tell me what the solution is?

**Comment by juninhoall** [comment]
how did you solve it?
