### ISSUE TITLE
[iOS] Purchases.checkTrialOrIntroDiscountEligibility not working

### ISSUE THREAD

**Issue by nijakobius** [RevenueCat/cordova-plugin-purchases#262]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

# Describe the bug

`Purchases.checkTrialOrIntroDiscountEligibility();` is not working. I am getting the following error in Xcode Console:

```
------ STARTUP JS ERROR ------
⚡️  TypeError: Purchases.checkTrialOrIntroDiscountEligibility is not a function. (In 'Purchases.checkTrialOrIntroDiscountEligibility()', 'Purchases.checkTrialOrIntroDiscountEligibility' is undefined)
```

Is this function not available in Cordova (https://www.revenuecat.com/docs/subscription-offers#checking-eligibility only mentions Swift)?

If it's not, how else can you check whether to promise a trial on our Subscription screen?

### Environment

   1. Platform: iOS
   2. SDK version: cordova-plugin-purchases@3.5.0
   3. OS + version: iOS 16.2
   4. XCode version: Version 14.2 (14C18)
   5. Framework (Cordova, Ionic, Ionic Native, etc): Cordova + Capacitor
   6. Framework version: @capacitor/ios@4.6.1
   7. How widespread is the issue. Percentage of devices affected: 100%

**Comment by codykerns** [comment]
@nijakobius hello! Looks like you might have the method name incorrect, try `checkTrialOrIntroductoryPriceEligibility` instead: https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/src/plugin/plugin.ts#L970

**Comment by nijakobius** [comment]
> @nijakobius hello! Looks like you might have the method name incorrect, try `checkTrialOrIntroductoryPriceEligibility` instead: https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/src/plugin/plugin.ts#L970

That's it! Thanks, although it would be helpful if the docs were updated :)
