### ISSUE TITLE
Android: Manifest merger failed

### ISSUE THREAD

**Issue by tgangso** [RevenueCat/cordova-plugin-purchases#30]
Not sure if capacitor or issue with this plugin, but any help would be appreciated.

Following this guide: https://ionicframework.com/docs/native/purchases

After adding the plugin, i get this error in android studio:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-43:19 to override.

**Comment by vegaro** [comment]
Hi @tgangso. Thanks for reporting. We haven't totally evaluated the compatibility with Capacitor yet so I am not sure if this error is due to our plugin not being compatible with Capacitor. I will evaluate it and come back to you here.

**Comment by tgangso** [comment]
@vegaro Thank you, hope there is an easy fix as revenuecat looks like a good solution

**Comment by jcesarmobile** [comment]
Looks related to the plugin using Android X.
You can try capacitor 2.0.0-beta.0 as it supports Android X

**Comment by aboedo** [comment]
@tgangso have you gotten a chance to try capacitor 2.0.0 as suggested by @jcesarmobile ? 
I just tried adding the plugin to a capacitor 2.0.0 app and didn't run into the same thing

**Comment by aboedo** [comment]
closing this out due to inactivity, feel free to reopen if it's still happening when using capacitor 2.0.0
