### ISSUE TITLE
iOS 13.4 - Payment not prompting

### ISSUE THREAD

**Issue by felipeclopes** [RevenueCat/cordova-plugin-purchases#33]
After updating my iOS phone to v13.4 RevenueCat stopped working. When calling 
`await this.purchases.purchaseProduct(this.PRODUCT_ID)` nothing happens, it returns successfully but do not open the payment prompts.

On release notes it is stated that they unified iPhone and iPad payments, which means there is a change in the payment system.

There are no logs or errors being thrown.

```
$ ionic info

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/felipeclopes/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.5, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.13.0 (/Users/felipeclopes/.nvm/versions/node/v12.13.0/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.4 Build version 11E146
```

```
$ ionic cordova plugin list
> cordova plugin ls
branch-cordova-sdk 4.1.2 "branch-cordova-sdk"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.3.0 "Facebook Connect"
cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"
cordova-plugin-health 1.1.3 "Cordova Health"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-purchases 1.0.5 "Purchases"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
sentry-cordova 0.17.0 "Sentry"
```

**Comment by rkotzy** [comment]
This seems to be a widespread issue with iOS 13.4. Can you try with a new sandbox user? 

Related: https://stackoverflow.com/questions/60907798/the-purchase-dialog-does-not-show-up-since-ios-13-4

**Comment by felipeclopes** [comment]
Do you have any information if that only happens in Sandbox?

**Comment by rkotzy** [comment]
I'm not able to reproduce this in sandbox but have seen other reports of it - nothing indicates this would happen in production. 

Does using a newly created sandbox user with no purchase history resolve this? Apple may have made some changes for Universal Purchases that aren't compatible with old sandbox purchases.

**Comment by felipeclopes** [comment]
I just tested in production and it is working, so it is a Sandbox issue only. I'll develop a workaround, but I was never able to reproduce proper payment workflow in Sandbox after the upgrade to 13.4

**Comment by rkotzy** [comment]
Did you try creating a new sandbox user that doesn't have any purchase history? Would be nice to come up with a workaround until Apple fixes this.

**Comment by felipeclopes** [comment]
My biggest problem is that the Apple testers don't use new sandbox users, so it is breaking for them and I can get the app approved. I'll skip payment in Sandbox and hope they don't need to revalidate the pricing/subscription.

**Comment by felipeclopes** [comment]
Just submitted the app skipping payment in Sandbox and the app got rejected. Do you have any suggested workaround?

**Comment by felipeclopes** [comment]
I'm facing a different issue today, it seems like the behavior is changing for some reason.

I initiated the Purchase object with `setDebugLogsEnabled` on `true` to get more info
```
this.purchases.setDebugLogsEnabled(true);
```

Then when I submit the `purchaseProduct` request as following
```
const response = await this.purchases.purchaseProduct(this.PRODUCT_ID);
```

I'm getting problems communicating with the App Store
```
ERROR: {"error":{"code":2,"message":"There was a problem with the App Store.","readable_error_code":"STORE_PROBLEM","underlyingErrorMessage":"Problem communicating with the Store when trying to validate the receipt.","readableErrorCode":"STORE_PROBLEM"},"userCancelled":false}
```

It might not be related, I just wanted to give as much information as I can to help.

**Comment by felipeclopes** [comment]
Do you have any updates on the original issue?

**Comment by vegaro** [comment]
We don't have any updates on this. None of us have been able to reproduce it yet either, but we are seeing reports of people hitting this.

> My biggest problem is that the Apple testers don't use new sandbox users

Did you test on your device with a new user and verified it works for new users?

> Any way I can force flush every transaction like suggested here https://stackoverflow.com/questions/60907798/the-purchase-dialog-does-not-show-up-since-ios-13-4 ?

Unless you setup the SDK using `observerMode` to true (which will not finish any transaction), all failed/successful transactions should be finished by our SDK.

**Comment by vegaro** [comment]
Fwiw, there is a partial sandbox outage (https://status.revenuecat.com/) since March 22nd that is probably causing a lot of the errors you are seeing. @bergergit reported error is most likely caused by it.

On top of that looks like on the update to 13.4 something changed in the iOS system (outside of RevenueCat's domain) and creating a new sandbox user should fix the problem as you have mentioned.

**Comment by vegaro** [comment]
@felipeclopes There have been more cases reported of people getting their app rejected due to the partial sandbox outage. Some people have had to submit their app twice or three times to pass the review.

**Comment by felipeclopes** [comment]
Our app just got approved, it seems like I faced 2 different issues:

[1] Inconsistent account state (can be fixed with new Sandbox account)
[2] Apple servers instability (needs luck)

Anyways, unless you have interest in investigating how to get to the inconsistent state in the Sandbox account, I would close the issue.

**Comment by vegaro** [comment]
Thanks for updating @felipeclopes 

Glad you managed to go through app review, it's been a hit and miss lately
