### ISSUE TITLE
Doesn't work in an Ionic React Capacitor project

### ISSUE THREAD

**Issue by planecore** [RevenueCat/cordova-plugin-purchases#38]
Hi! I can't get cordova-plugin-purchases to work in my project.
I'm using Ionic React with Capacitor and TypeScript.
I tried to install it like any Cordova plugin in Capacitor:

```
npm install cordova-plugin-purchases --save
ionic cap sync
```

But it doesn't work:

`Module not found: Can't resolve 'cordova-plugin-purchases'`

**Comment by vegaro** [comment]
Hi @planecore. I have just successfully created a React Capacitor project and added the plugin. I added the Ionic native wrapper too so that the TypeScript types can be used:

```
// Install Cordova plugin
npm install cordova-plugin-purchases

// Install Ionic Native core library (once per project)
npm install @ionic-native/core

// Install TypeScrypt wrapper
npm install @ionic-native/purchases

// Update native platform project(s) to include newly added plugin
ionic cap sync
```

I just improved the docs at https://docs.revenuecat.com/docs/ionic so that the installation is more clear.

**Comment by planecore** [comment]
It works! Thanks!
