### ISSUE TITLE
Export typescript types

### ISSUE THREAD

**Issue by hexsprite** [RevenueCat/cordova-plugin-purchases#41]
Since you wrote this plugin in TS it would be amazing to have the types available to be consumed in an application.

**Comment by aboedo** [comment]
Hi! thanks for bringing this to our attention, we're fixing it in https://github.com/RevenueCat/cordova-plugin-purchases/pulls

**Comment by vegaro** [comment]
Hi! We have released 1.2.0 that should export the types correctly. Let us. know if you find any issues. 

Thanks for bringing this to our attention!!
