### ISSUE TITLE
strip-frameworks.sh: No such file or directory

### ISSUE THREAD

**Issue by MGmotors** [RevenueCat/cordova-plugin-purchases#48]
1. Environment
    1. Platform: iOS
    2. SDK version: 1.2.0
    3. OS version: macOS Catalina 10.15.3
    4. XCode version: 11.5

I followed the [installation guide for cordova](https://docs.revenuecat.com/docs/cordova) and added the "Strip Frameworks Phase" as described.   
The build for iOS with XCode now fails with:
      
"**[...]/cordova/platforms/ios/../../node_modules/cordova-plugin-purchases/src/ios/strip-frameworks.sh: No such file or directory   
Command PhaseScriptExecution failed with a nonzero exit code**"
   
I saw the commit 4a3616630d12d8e4c594fa6e1f1e32bd896fa8b9 in this repository that removes the file. Is the installation guide just not up to date? Is the "Strip Frameworks Phase" no longer needed?

**Comment by aboedo** [comment]
hi! 👋 thanks for reporting. The docs are indeed outdated, that step is no longer needed since we're now relying on cocoapods for that. 
We'll update the docs to reflect it.

**Comment by corysmc** [comment]
Just ran into this same issue - thanks for the quick reply!

**Comment by vegaro** [comment]
We added a section here https://docs.revenuecat.com/docs/cordova#add-strip-frameworks-phase-if-using-cordova-plugin-purchases-110-or-lower, but just in case I paste the solution here for future reference.

Basically, if using version 1.1.0 or lower of this plugin (before we added cocoapods), these extra steps are required:

1. In Xcode, in project manager, select your app target.
1. Open the Build Phases tab
1. Add a new Run Script, name it Strip Frameworks
1. Add the following command "${PROJECT_DIR}/../../node_modules/cordova-plugin-purchases/src/ios/strip-frameworks.sh" (quotes included)

**Comment by nijakobius** [comment]
> hi! 👋 thanks for reporting. The docs are indeed outdated, that step is no longer needed since we're now relying on cocoapods for that.
> We'll update the docs to reflect it.

This is still in the docs it seems...

**Comment by aboedo** [comment]
@nijakobius yeah, we couldn't entirely remove it because devs can still use older versions of the SDK where it's still needed. But we did attempt to clarify it by stating `Add Strip Frameworks Phase if using cordova-plugin-purchases 1.1.0 or lower`
