### ISSUE TITLE
Calling "Purchases.identify" several times can block/interrupt the code flow (no error, no result or success callback is called) 

### ISSUE THREAD

**Issue by uareurapid** [RevenueCat/cordova-plugin-purchases#55]
Description,

To set the identity or better help to identify a given user, we can call the Purchases.identify(uid, successCallback, errorCallbac) function. We provide a user identifier and we should get either the updated info or some error. In a scenario where this is called multiple times it can prevent the execution of the next lines of the code, since it never returns.

1. Environment
    1. Platform: IOS
    2. SDK version: latest 1.2.2  (and prior versions) + Cordova IOS 6.0
    3. OS version: IOS 14,13,12 and possibly others
    4. XCode/Android Studio version: Latest Xcode 12
    5. How widespread is the issue. Percentage of devices affected. NA

2. [Debug logs] . There are no logs because the execution is not returned to the main program (the lines of code after this call are never executed)

3. Steps to reproduce:

To reproduce we can call Purchases.identify multiple times on the same app execution. For instance, lets suppose we have a button that opens the paywall screen with a list of available subscriptions for the user to purchase. Before showing the paywall we call the function to set an identifier for the user.. Then close the paywall page and repeat the process, a few times. Eventually the execution will get stuck at some point, because the function Purchases.identify blocks, and the execution is not returned to the caller block, no error is logged on screen, and neither the error or success callbacks are ever called. This means that any block of code right after this call, will never be called, and the app flow will have to continue on some other point.

4. A simple suggestion, would be just return an error if we already identified the user for the session, or eventually report the operation as successful if nothing changed. In any case, the execution should always return to the main caller block. An additional message could also be logged to help tracking similar events. A workaround is to make sure this is not called more than once on every app execution

**Comment by uareurapid** [comment]
Just as a follow up, in case anyone is interested. This also seems happens randomly even if only 1 call is made. It looks like in certain occasions something is "not initialised". The big problem is that this call can completely block the app flow, since neither a success or error callback is invoked. The only workaround is to have some timeout to continue execution, if we don't return from the call after some time

**Comment by rkotzy** [comment]
Hi 👋. Are you able to provide the RevenueCat debug logs that reproduce this? https://docs.revenuecat.com/docs/debugging

That may help understand a little better what is going on under-the-hood. If you call .identify() with the current app user Id the SDK will no-op and return the completion block right away.

**Comment by uareurapid** [comment]
Hi, thanks for the reply. Debugging was already ON, but doesn't change anything cause there is no debug code there (no output). In any case I was able to found the issue (at least for the last case, but probably it was all related anyway). Our backend identifies users with a random user id. It's a numeric identifier. Your plugin is enforcing & expecting something of type "string" ONLY, but this is not clearly stated on the documentation (the same identifier was being interpreted correctly in other occasions).  So, at the end, I was only able to understand the problem by looking directly at your source code: 
```
public static identify(
    newAppUserID: string,
    callback: (purchaserInfo: PurchaserInfo) => void,
    errorCallback: (error: PurchasesError) => void
  ) {
    // noinspection SuspiciousTypeOfGuard
    if (typeof newAppUserID !== "string" || newAppUserID === "") {
      throw new Error("newAppUserID is a required string and cannot be empty");
    }
    window.cordova.exec(callback, errorCallback, PLUGIN_NAME, "identify", [
      newAppUserID,
    ]);
  }
```
What happens here is that the `**typeof**` fails, and you're just throwing an error, without calling the error callback.. so, unless there is a `try {} catch()` block wherever this function is getting called it will simply not return execution to the calling code flow.. Imo, throwing errors is usually not the best approach when we're providing error and success handlers to a call, particularly when we don't state that in the documentation. It's expectable that at least the error handler would be called :-) .. By the way, the same handling is done on other functions of the plugin

Anyway, I think that would be all

thank you & best regards
