### ISSUE TITLE
Methods not executing in UI thread

### ISSUE THREAD

**Issue by vegaro** [RevenueCat/cordova-plugin-purchases#58]
**Describe the bug**
There have been some reports in the past of the functions not being executed in the main thread. I was looking into it and the annotation we use doesn't change to UI thread when we specify MAIN thread. We have to annotate with thread UI instead.

1. Environment
    1. Platform: Android

**Comment by beylmk** [comment]
@vegaro going through old issues, is this something to add to sharpen the saw?

**Comment by vegaro** [comment]
It's already done. I should have closed this issue when I merged this PR https://github.com/RevenueCat/cordova-plugin-purchases/pull/66 😄
