### ISSUE TITLE
After upgrade to version 1.3.0 On iOS Build appears The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0.

### ISSUE THREAD

**Issue by juanico18** [RevenueCat/cordova-plugin-purchases#59]
After upgrade to version 1.3.0 On iOS Build appears The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0.

What can I do?

**Comment by aboedo** [comment]
Hi! Sorry about the inconvenience. We're looking for ways to improve the plugin so that this isn't needed. In the meantime, if you open up your project in Xcode, you can find the needed setting under `Swift Language Version`. 
Setting it to `Swift 5` should fix it. 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/3922667/95581559-95444a80-0a0f-11eb-8ac2-43b2a93fc74c.png">

**Comment by juanico18** [comment]
Strange thing is that is already set
![Captura de pantalla 2020-10-09 a las 14 21 41](https://user-images.githubusercontent.com/2843278/95582407-e9185900-0a3a-11eb-98b7-d9e72ad0a4db.png)

**Comment by aboedo** [comment]
interesting. In the screenshot, it appears like the target that has this set is `Pods`. There should be at least one more target, the one for your app, that needs to have it set. Have you checked that one too?

**Comment by juanico18** [comment]
Main problem in fact is that I am trying to update the plugin because when I am using version 1.2.0 And distribute to AppStore I am getting this error: https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/

Do you know if the plugin is using some reference to UIWebView instead of WKWebView?

**Comment by aboedo** [comment]
the plugin doesn't use any form of a webView, this sounds like it might be coming from a different plugin.

**Comment by aboedo** [comment]
@juanico18 please confirm if you found the plugin causing the issues and if the `Swift Language Version` setting got you past the initial error.

**Comment by juanico18** [comment]
Hello @aboedo Finally I revert the upgrade to version 1.2.0 and fix for other plugin the UIWebView problem. By now I will not be testing the upgrade to 1.3.0. When I will try again I will let you know if still appears the problem

**Comment by aboedo** [comment]
@juanico18 I'm closing this for now, however we've added a section to our docs for cordova with instructions to set the Swift language version, available here. Let us know if you encounter any issues once you do upgrade!

**Comment by juanico18** [comment]
Thanks @aboedo It works for us.

**Comment by aboedo** [comment]
@juanico18 thanks for the update! I'm glad it's working
