### ISSUE TITLE
getProducts: Invalid callback id received by sendPluginResult 

### ISSUE THREAD

**Issue by solojuve1897** [RevenueCat/cordova-plugin-purchases#6]
Calling method like this:

```
Purchases.getProducts(['com.xxx.app.prem1', 'com.xxx.app.prem3', 'com.xxx.app.prem6'], 
   products => {
    console.log(products)
  },
  error => {
    console.log(error)
  })
```

Have the following in the log:

`Invalid callback id received by sendPluginResult To Native Cordova ->  PurchasesPlugin getProductInfo PurchasesPlugin876175322 ["options": [<__NSArrayM 0x281b13a50>( com.xxx.app.prem1, com.xxx.app.prem3, com.xxx.app.prem6 ) , subs]]
`

Though the call is successful and I recieve the complete list of products from the store.

Tested with iOS Sandbox.

**Comment by aboedo** [comment]
closing this ticket due to inactivity, feel free to reopen if it's still happening.
