### ISSUE TITLE
Error when downgrading a subscription using prorationMode: DEFERRED

### ISSUE THREAD

**Issue by echonox** [RevenueCat/cordova-plugin-purchases#65]
**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

Its the same issue reported and fixed here:
https://github.com/RevenueCat/purchases-android/pull/200
https://github.com/RevenueCat/purchases-android/issues/165
https://docs.revenuecat.com/discuss/5ee8be78ac4d12005c1765bb

1. Environment
    1. Platform: Android Cordova
    2. SDK version: 1.3.2
    3. OS version: 10
    4. XCode/Android Studio version: 4.0.1
    5. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
No debug option for the cordova plugin in the docs
3. Steps to reproduce, with a description of expected vs. actual behavior
- Purchase a higher monthly subscription on android
- Downgrade  the subscription to a cheaper monthly option by passing `oldSku` and `prorationMode: DEFERRED`
- excepted: success callback that the downgrade was ok
- actually: error callback returned with error:
`code: 2
message: "There was a problem with the Play Store."
readableErrorCode: "StoreProblemError"
readable_error_code: "StoreProblemError"
underlyingErrorMessage: "Error updating purchases. DebugMessage: . ErrorCode: SERVICE_UNAVAILABLE."`
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
https://github.com/RevenueCat/purchases-android/pull/200
https://github.com/RevenueCat/purchases-android/issues/165
https://docs.revenuecat.com/discuss/5ee8be78ac4d12005c1765bb

**Comment by vegaro** [comment]
Thanks for opening @echonox . Will throw a release soon including the more recent version of the Android SDK that includes this fix. Will keep this open until then

**Comment by echonox** [comment]
@vegaro any update when will the release will happen?

**Comment by GrahamDi** [comment]
@vegaro I have also seen the issue with DEFERRED as described here: https://docs.revenuecat.com/discuss/5ee8be78ac4d12005c1765bb
and addressed in: https://github.com/RevenueCat/purchases-android/pull/200 (**as per @echonox question, has this been released yet?**)

However, I am experiencing it when using purchases_flutter so the fix to purchases_android won't help me (and other Flutter users) I believe.

When will this fix be made to the purchases_flutter package?

**Comment by GrahamDi** [comment]
We are awaiting a response from @vegaro to the questions above.

**Comment by vegaro** [comment]
Sorry I missed your question @GrahamDi . Versions above 2.0.0 of the Flutter package should have the fix. Let us know if you're still seeing issues

**Comment by GrahamDi** [comment]
Thanks @vegaro and no worries. 

I will retest asap. 

I opted for one of the other proration methods (can't remember which and am on my phone answering this) and may well  stay with it going forward.

**Comment by echonox** [comment]
> Sorry I missed your question @GrahamDi . Versions above 2.0.0 of the Flutter package should have the fix. Let us know if you're still seeing issues

@vegaro and for cordova?

**Comment by aboedo** [comment]
@echonox versions of `cordova-plugin-purchases` above 2.0.0 have the fix, I think @vegaro meant Cordova instead of Flutter

**Comment by vegaro** [comment]
Just to clarify, @GrahamDi was asking about `purchases_flutter` package, for which versions 2.0.0 has the fix. @echonox, as @aboedo mentioned, `cordova-plugin-purchases` above 2.0.0 also have the fix. Sorry for the confusion.

Closing since it's been solved.
