### ISSUE TITLE
IOS - how to force subscription re-activation within the app

### ISSUE THREAD

**Issue by paulovargatt** [RevenueCat/cordova-plugin-purchases#68]
**Describe the bug**
Using renewable signatures, we realized that when making the first purchase the app invokes the store normally by subscribing, but when the cancellation occurs and a new purchase attempt simply does nothing happens! The plugin returns the subscription already expired.

Is there any way to force the reactivation of subscriptions within the app?

perhaps related to: [Apple Forum](https://developer.apple.com/forums/thread/662914?login=true&page=1#645958022)

1. Environment
    1. Platform: cordova 9
    2. SDK version: 1.3.2
    3. OS version: 14.2
    4. XCode: 12.2
    5. Tested on em ios 13, 14.1, 14.2
3. Steps to reproduce, with a description of expected vs. actual behavior: Sign up in a testfly subscription, wait for cancellation, try to sign up again. Previously it was possible to re-sign the user within the application, now the plugin returns his last signature.

**Comment by rkotzy** [comment]
I wasn't able to reproduce this in a sample app, users shouldn't have any trouble re-purchasing a subscription after expiration. 

Can you provide the RevenueCat debug logs that reproduce the issue? https://docs.revenuecat.com/docs/debugging

Also, can you try creating a new sandbox user and Apple and testing with that new account.
