### ISSUE TITLE
regarding addPurchaserInfoUpdateListener

### ISSUE THREAD

**Issue by solojuve1897** [RevenueCat/cordova-plugin-purchases#7]
With React Native the documentation says one can do the following:

```
Purchases.addPurchaserInfoUpdateListener(info => {
	// handle any changes to purchaserInfo
});
```

I don't think this works with a Cordova-powered app just yet. Is this correct, or am I doing something wrong? If it doesn't exist as of yet, when will this be added?

**Comment by vegaro** [comment]
The way Cordova handles this is a little bit different. You can subscribe to the window event `onPurchaserInfoUpdated` to get any changes that happen in the `purchaserInfo`. We do the following anytime we detect a change:
```
        window.cordova.fireWindowEvent("onPurchaserInfoUpdated", purchaserInfo);
```

**Comment by solojuve1897** [comment]
Thanx. Should maybe be in the docs if it's not. I didn't see it.
