### ISSUE TITLE
Update Google Billing Library

### ISSUE THREAD

**Issue by michalsisak** [RevenueCat/cordova-plugin-purchases#81]
Hello,

In the Google Play dashboard there is an alert warning about old version of Google Billing Client. From November version 2 will not be accepted, only version 3. 
[More info](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html).

Can you please update this library to prevent further alerts? Thank you

**Comment by aboedo** [comment]
hi! 👋 

Versions >= 1.3.0 of this plugin use Google Billing >= 3.0.0. 
In particular, the latest version (2.1.1) uses Google Billing Library 3.0.2. 

If you haven't yet, please upgrade your plugin version.
