### ISSUE TITLE
Incorrect Type For PurchasesOffering['availablePackages']

### ISSUE THREAD

**Issue by corbmanj** [RevenueCat/cordova-plugin-purchases#93]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

I believe there is an error in the type for PurchasesOffering['availablePackages']. The current type is
```
    /**
     * Array of `Package` objects available for purchase.
     */
    readonly availablePackages: [PurchasesPackage];
```
However, if this is really supposed to be an array of PurcahsesPackages then the correct syntax for that is 
`readonly availablePackages: PurchasesPackage[];`

**Additional context**
This is causing issues when trying to use this package in a typescript project.

Link to PR:
https://github.com/RevenueCat/cordova-plugin-purchases/pull/94

**Comment by vegaro** [comment]
I have merged your PR and also this other PR https://github.com/RevenueCat/cordova-plugin-purchases/pull/95 fixing the build. This will go with the next release.

Thanks for reporting and for opening the issue!

**Comment by corbmanj** [comment]
@vegaro what's the process to get the version bumped in @ionic-native? They're still on 2.1.1 (also, thanks for merging!)

**Comment by vegaro** [comment]
@beylmk is going to be upgrading the version in Ionic Native. We need to open a PR against their repo so it might take some time to get released on their end though

**Comment by beylmk** [comment]
Hey @corbmanj, just a heads up that this was merged and we have a new ionic-native version, 2.3.0. See the PR [here](https://github.com/ionic-team/ionic-native/pull/3702/files).

I'm going to go ahead and close this issue since the fix is out, but feel free to re-open it if you have any issues!
